# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dj_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_approved', models.CharField(max_length=20)),
                ('comment_type', models.CharField(max_length=20)),
                ('comment_date', models.DateField()),
                ('comment_author_IP', models.CharField(max_length=200)),
                ('comment_author_URL', models.URLField()),
                ('comment_author_email', models.CharField(max_length=100)),
                ('user_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dj_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.TextField()),
                ('comment_count', models.IntegerField()),
                ('post_type', models.CharField(max_length=20)),
                ('post_modified', models.DateField()),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dj_comments',
            name='comment_post_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Dj_post'),
        ),
    ]
