# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dj_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dj_post',
            name='post_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Dj_category'),
        ),
    ]
